services:
  web:
    build: .
    container_name: analytics-processor
    restart: unless-stopped
    depends_on:
      - jaeger
      - redis
    environment:
      - ENVIRONMENT=test
      - PORT=8080
      - JAEGER_ENDPOINT=jaeger:4318
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    ports:
      - "8080:8080"
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4318:4318"
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge
